### ISSUE TITLE
DAT file: DOSBox games in the Menu

### ISSUE THREAD

**Issue by RobLoach** [libretro/dosbox-libretro#44]
Creating a [DOS.dat file](https://github.com/libretro/libretro-database/blob/master/dat/DOS.dat) for the DOSBox core would mean we could launch DOSBox games from the RetroArch menu.

The [Total DOS Collection](http://pc.nugnugnug.com/master/) provides a DAT file containing all files. We could use this as a base, and create a script that would extract `.exe` files from it, and have their entries appear in the RA Menu.

## TODO

- [x] Obtain the latest TDC DAT (currently 12)
- [x] Remove all file entries except .exe files
- [x] Remove the date from every file date 1992/04/21 23:09:36
- [ ] Remove the year from the name (1991)
- [ ] Remove the company names (Apogee Software, Ltd.)
- [ ] Remove the genre [Action]
- [x] Remove the file extension from the name .zip
- [x] Remove installer entries, games that have (Installer) in the name
- [x] Rename `file (` entries to `rom (`

**Comment by RobLoach** [comment]
Commited the first iteration of [DOS.dat at libretro-database](https://github.com/libretro/libretro-database/blob/master/dat/DOS.dat).

Going to tackle the rest of the issues in the queue over at:
https://github.com/RobLoach/libretro-database-dos/issues
